### ISSUE TITLE
Playing video without audio

### ISSUE THREAD

**Issue by Rrod8607** [appunite/AndroidFFmpeg#11]
Great job with this project by the way, I was able to fairly easily integrate the player
into an App.  I'm trying to use it mainly to process mpeg2 TS streams.
Some files of the mpeg2 TS format play fine, some don't.
Below is a partial logcat of a file that won't play, I wonder if anything jumps out that could shed some light on why it won't play.
The App error is "Could not open stream (FFmpegPlayer error -1).
The logcat is below:
======================================================================
V/ffmpeg  ( 2058): Non-increasing DTS in stream 0: packet 148 with DTS 20447427, packet 149 with DTS 20447427
I/ffmpeg  ( 2058): Current profile doesn't provide more RBSP data in PPS, skipping
V/ffmpeg  ( 2058): first_dts 20027007 not matching first dts 19993974 in que
V/ffmpeg  ( 2058): first_dts 20027007 not matching first dts 19993974 in que
V/ffmpeg  ( 2058): first_dts 20027007 not matching first dts 19993974 in que
V/ffmpeg  ( 2058): first_dts 20027007 not matching first dts 19993974 in que
V/ffmpeg  ( 2058): Non-increasing DTS in stream 0: packet 152 with DTS 20462442, packet 153 with DTS 20462442
V/ffmpeg  ( 2058): first_dts 20027007 not matching first dts 19993974 in que
V/ffmpeg  ( 2058): Non-increasing DTS in stream 0: packet 153 with DTS 20462442, packet 154 with DTS 20462442
I/ffmpeg  ( 2058): Current profile doesn't provide more RBSP data in PPS, skipping
V/ffmpeg  ( 2058): first_dts 20027007 not matching first dts 19993974 in que
E/ffmpeg  ( 2058): max_analyze_duration 5000000 reached at 5005000
E/ffmpeg  ( 2058): Could not find codec parameters for stream 1 (Unknown: none ([6][0][0][0] / 0x0006)): unknown codec
E/ffmpeg  ( 2058): Consider increasing the value for the 'analyzeduration' and 'probesize' options
V/ffmpeg  ( 2058): File position after avformat_find_stream_info() is 0
W/ffmpeg  ( 2058): Input #0, mpegts, from 'file:///mnt/sdcard/Download/RAVENH264.ts':
W/ffmpeg  ( 2058):   Duration: 
W/ffmpeg  ( 2058): 00:01:52.81
W/ffmpeg  ( 2058): , start: 
W/ffmpeg  ( 2058): 222.155267
W/ffmpeg  ( 2058): , bitrate: 
W/ffmpeg  ( 2058): 2845 kb/s
W/ffmpeg  ( 2058): 
W/ffmpeg  ( 2058):   Program 1 
W/ffmpeg  ( 2058):     Stream #0:0
W/ffmpeg  ( 2058): [0x11]
V/ffmpeg  ( 2058): , 155, 1/90000
W/ffmpeg  ( 2058): : Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 720x480 [SAR 1:1 DAR 3:2], 1001/60000
W/ffmpeg  ( 2058): , 30.58 fps
W/ffmpeg  ( 2058): , 29.97 tbr
W/ffmpeg  ( 2058): , 90k tbn
W/ffmpeg  ( 2058): , 59.94 tbc
W/ffmpeg  ( 2058): 
W/ffmpeg  ( 2058):     Stream #0:1
W/ffmpeg  ( 2058): [0x21]
V/ffmpeg  ( 2058): , 51, 1/90000
W/ffmpeg  ( 2058): : Unknown: none ([6][0][0][0] / 0x0006)
W/ffmpeg  ( 2058): 
I/player.c( 2058): player_set_data_source Number of streams: 2
I/player.c( 2058): - stream: 0
I/player.c( 2058): -- metadata:
I/player.c( 2058): -- codec_name: 
I/player.c( 2058): -- codec_type: video
I/player.c( 2058): - stream: 1
I/player.c( 2058): -- metadata:
I/player.c( 2058): -- codec_name: 
I/player.c( 2058): -- codec_type: other
I/player.c( 2058): player_find_stream, type: 0
I/player.c( 2058): player_open_stream trying open: 28
V/ffmpeg  ( 2058): detected 2 logical cores
I/player.c( 2058): player_open_stream opened: 28
I/player.c( 2058): player_set_data_source 4
I/player.c( 2058): player_set_data_source Video size is [720 x 480]
I/player.c( 2058): player_find_stream, type: 1
I/player.c( 2058): player_set_data_source error
I/player.c( 2058): player_set_data_source close_file
V/ffmpeg  ( 2058): Statistics: 3035280 bytes read, 3 seeks
I/player.c( 2058): player_set_data_source end
============================================================================
Based on the above logcat, is there any light you can shed on cause of error and/or potential
fixes ?

Also I expect some of the TS streams will have multiple/many errors, is there anything that can be
done to allow greater tolerance for streams with errors ?

Thanks for your time and attention on this!

**Comment by jacek-marchwicki** [comment]
Fixed
