### ISSUE TITLE
unable to checkout x264

### ISSUE THREAD

**Issue by shalinashiyan** [appunite/AndroidFFmpeg#113]
Hi, 
I like this project but I am not able to checkout x264. I got this error in "git submodule update" stage. 
Could you update the git x264 repository? Thanks. 

Submodule path 'FFmpegLibrary/jni/vo-amrwbenc': checked out '6ffcea9040b23bde4741cac182f563f56bde4379'
Cloning into 'FFmpegLibrary/jni/x264'...
remote: Counting objects: 18269, done.
remote: Compressing objects: 100% (3409/3409), done.
remote: Total 18269 (delta 15072), reused 18000 (delta 14818)
Receiving objects: 100% (18269/18269), 4.34 MiB | 503.00 KiB/s, done.
Resolving deltas: 100% (15072/15072), done.
Checking connectivity... done.
fatal: reference is not a tree: 999b753ff0f4dc872077f4fa90d465e948cbe656
Unable to checkout '999b753ff0f4dc872077f4fa90d465e948cbe656' in submodule path 'FFmpegLibrary/jni/x264'
shalina@shalina-Inspiron-1720:~/test/AndroidFFmpeg$ ls -al

Thanks
Shalina

**Comment by jacek-marchwicki** [comment]
Please try to use git submodule sync

modules surely can be downloaded because travis build is green

**Comment by shalinashiyan** [comment]
Thanks but we did "git submodule sync" before "git submodule update" and the error shown above was the one we saw. In the "git submodule sync", we did see "FFmpegLibrary/jni/x264" got listed but we couldn't check it out.

**Comment by jacek-marchwicki** [comment]
Did you commited some changes in root project because master bracnch of ffmpeg refers to 121396c71b4907ca82301d1a529795d98daab5f8
look here:
https://github.com/appunite/AndroidFFmpeg/tree/master/library-jni/jni

but your git trying to fetch `999b753ff0f4dc872077f4fa90d465e948cbe656` this is something wrong..
maybe try to download project from scretch

**Comment by dzungpv** [comment]
I have the same problem, can not "git submodule update" with this error.

**Comment by jacek-marchwicki** [comment]
@dzungpv do you have newest master brach?

**Comment by dzungpv** [comment]
@jacek-marchwicki , just miss 1 commit,  i will retry now.

**Comment by dzungpv** [comment]
@jacek-marchwicki Still the same. You can try clone in difference folder.
I use this: git clone https://review.appunite.com/androidffmpeg AndroidFFmpeg

**Comment by dzungpv** [comment]
@jacek-marchwicki 
Sorry, this is a copy paste error. I copy your guide to terminal and not check the link, it not github one.
You can edit the guide so no body will face this again.

**Comment by jacek-marchwicki** [comment]
Sorry guys.. we no longer use gerrit for this project

Updated readme here: https://github.com/appunite/AndroidFFmpeg/pull/119
