### ISSUE TITLE
repository 'https://gitorious.org/tropicssl/tropicssl.git/' not found

### ISSUE THREAD

**Issue by swsachini** [appunite/AndroidFFmpeg#122]
submodule update fails with the error message.

fatal: repository 'https://gitorious.org/tropicssl/tropicssl.git/' not found

**Comment by jacek-marchwicki** [comment]
@swsachini please find some other mirror of tropicssl and change it your submodules

**Comment by jacek-marchwicki** [comment]
github acquired gitorious so they will be unaccessable

**Comment by bsysop** [comment]
This forks works perfect.
https://github.com/axic/tropicssl

Just change submodule files.
