### ISSUE TITLE
Audio playback issues with wmapro (fix included)

### ISSUE THREAD

**Issue by matthewn4444** [appunite/AndroidFFmpeg#124]
Hi, I forked this repo a long time ago and cannot easily create a pull request.

I fixed an audio decoding issue with wmapro (and maybe more) in my repo where it would only decode a portion of the audio packet, free it and get a new one, causing the audio to crash (where the next decode would throw at `avcodec_decode_audio4`).

Look at my change for more details:
https://github.com/matthewn4444/VPlayer_lib/commit/710a835f66ef4759fea80ed78e9791a98745719c

**Comment by jacek-marchwicki** [comment]
@matthewn4444 thanks for you work, I just merged your change here: https://github.com/appunite/AndroidFFmpeg/pull/126
BTW: I already merged some changes to AndroidFFmpeg, thanks :)
