### ISSUE TITLE
Cloning into submodule 'library-jni/jni/libyuv' failed.

### ISSUE THREAD

**Issue by ms88privat** [appunite/AndroidFFmpeg#137]
I can't get this project to work. I installed all requirements on ubuntu. 

It fails at the step "git submodule update". 

```
Cloning into 'library-jni/jni/libass'...
remote: Counting objects: 6014, done.
remote: Total 6014 (delta 0), reused 0 (delta 0), pack-reused 6014
Receiving objects: 100% (6014/6014), 2.07 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (3956/3956), done.
Checking connectivity... done.
Submodule path 'library-jni/jni/libass': checked out 'de409235f4a32f6dfa6ab73eeb4bcd8d3b679387'
Cloning into 'library-jni/jni/libyuv'...
fatal: https://git.chromium.org/external/libyuv.git/info/refs not valid: is this a git repository?
Clone of 'https://git.chromium.org/external/libyuv.git' into submodule path 'library-jni/jni/libyuv' failed
```

If I ignore this error and follow the next steps i will receive
```
./build_android.sh: line 121: ./configure: No such file or directory
```

Any idea?

Thanks

**Comment by jacek-marchwicki** [comment]
@ms88privat try to `git submodule sync` before `git module update` if submodules will not fetch you will not be able to compile code ;)

**Comment by ms88privat** [comment]
@jacek-marchwicki I did sync before :/

**Comment by gen2brain** [comment]
Url is changed now to https://chromium.googlesource.com/external/libyuv . Just replace url in .gitmodules and .git/config .

**Comment by CKY91** [comment]
hi, is this the reason that causes 

./build_android.sh: line 121: ./configure: No such file or directory

?
