### ISSUE TITLE
'Could not find compilator'

### ISSUE THREAD

**Issue by okarakose** [appunite/AndroidFFmpeg#153]
I did all commands which are writing on installation section of wiki.

**./fetch.sh** 

./autogen.sh: 1: ./autogen.sh: aclocal: not found
./autogen.sh: 55: test: -lt: argument expected
./autogen.sh: 59: test: -gt: argument expected
./autogen.sh: 67: test: -lt: argument expected
./autogen.sh: 71: test: -gt: argument expected
./autogen.sh: 1: ./autogen.sh: libtoolize: not found
./autogen.sh: 55: test: -lt: argument expected
./autogen.sh: 59: test: -gt: argument expected
./autogen.sh: 67: test: -lt: argument expected
./autogen.sh: 71: test: -gt: argument expected
./autogen.sh: 1: ./autogen.sh: autoconf: not found
./autogen.sh: 55: test: -lt: argument expected
./autogen.sh: 59: test: -gt: argument expected
./autogen.sh: 67: test: -lt: argument expected
./autogen.sh: 71: test: -gt: argument expected
generating `configure.ac'
running`aclocal -I . --force'
./autogen.sh: 1: eval: aclocal: not found
error while running `aclocal -I . --force'

**./build_android.sh** 

`+ '[' /home/android-ndk-r8e = '' ']'
- '[' -z '' ']'
- DIRECTORIES='/home/android-ndk-r8e/toolchains/arm-linux-androideabi-*'
- for i in '$DIRECTORIES'
- PROPOSED_NAME='*'
- [[ \* =~ ^[0-9.]+$ ]]
- '[' -z '' ']'
- echo 'Could not find compilator'
  Could not find compilator
- exit 1
  `

**Comment by guanguodong999** [comment]
Did you solve the problem？

**Comment by okarakose** [comment]
unfortunately.. I am still waiting the best way to use ffmpeg library on android platform.

**Comment by guanguodong999** [comment]
only do it yourself.   o_O
