### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by vfa-tuantt** [appunite/AndroidFFmpeg#165]
Hi,
I'm facing with big issue. 
I checkout and build source code but i got this message
```
Because we have local pkg-config we will create it in /Users/tranthanhtuan/Downloads/android-ndk-r10e/toolchains/mipsel-linux-android-4.9/prebuilt/darwin-x86_64/bin/mipsel-linux-android-pkg-config directory using /usr/local/bin/pkg-config
```
Could you please help me to resolve this issue? I hope your reply.
Thank you very much

**Comment by jacek-marchwicki** [comment]
This is not an issue, this is a information log - so you need to look somewhere else
