### ISSUE TITLE
Crash when player->caputre_streams_no has negative value

### ISSUE THREAD

**Issue by myrmidon-media** [appunite/AndroidFFmpeg#36]
Sometimes a negative  value of player->caputre_streams_no is passed to player_find_stream() when playing certain streams. Thus a crash happens in:

```c
player->input_streams[streams_no] = stream;
```

To avoid this we can check before reaching that point.

```c
if(streams_no < 0){
		 LOGI(3, "streams_no %d", streams_no);
		 return -1;
}
```

Doing that we'll reach goto error in:

```c
if ((player->video_stream_no = player_find_stream(player,
		AVMEDIA_TYPE_VIDEO, video_stream_no)) < 0) {
		err = player->video_stream_no;
		goto error;
}

```

But another crash will happen in player_alloc_video_frames_free() due to uninitialized pointers in any of the "free" procedures, for example:

```c
//player->tmp_frame2 pointer is not NULL but it's unintialized
if (player->tmp_frame2 != NULL) {
               //CRASH
		avcodec_free_frame(&player->tmp_frame2);
		player->tmp_frame2 = NULL;
	}
```

One possible solution it's to initialize pointers to NULL:

```c

int jni_player_init(JNIEnv *env, jobject thiz) {

.....
	
	//Initialize pointers for sanity reasons
	
+	player->rgb_frame = NULL;
+	player->rgb_frame = NULL;
+	player->tmp_frame2 = NULL;
+	player->tmp_buffer = NULL;
+	player->tmp_buffer2 = NULL;


...
}
```

**Comment by jacek-marchwicki** [comment]
Fixed by: https://github.com/appunite/AndroidFFmpeg/commit/242c8870e2d34dccf70246ea31fc2e976ea79a53 My issue
