### ISSUE TITLE
Freetype became Freetype2: wont compile

### ISSUE THREAD

**Issue by dlowerre** [appunite/AndroidFFmpeg#39]
I wonder if you are aware that freetype became freetype2 since you posted this.  

I managed to get to the build_android.sh step but it dies trying to compile freetype2 with errors like this:

In file included from /Users/dlowerre/AndroidFFmpeg/FFmpegLibrary/jni/freetype2/include/freetype/freetype.h:35,
                 from /Users/dlowerre/AndroidFFmpeg/FFmpegLibrary/jni/freetype2/include/freetype/internal/ftdebug.h:30,
                 from /Users/dlowerre/AndroidFFmpeg/FFmpegLibrary/jni/freetype2/src/base/ftsystem.c:30:
/Users/dlowerre/AndroidFFmpeg/FFmpegLibrary/jni/freetype2/include/freetype/fttypes.h:172: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FT_Tag'

**Comment by jacek-marchwicki** [comment]
You can now look on .travis.yml file. Travis CI ensure that everything compile
