### ISSUE TITLE
Are you planning to add video encoding support to your library?

### ISSUE THREAD

**Issue by nolovelust** [appunite/AndroidFFmpeg#40]
As per subject, Are you planning to add video encoding support to your library?
Reason I am asking that I don't know C and an interface from within library would be good? Or any direction as to how to achieve it.

there are other ports of ffmpeg for Android but most of them does not compile or create one executable that can only run as cmd line app

**Comment by jacek-marchwicki** [comment]
@nolovelust nope, no plans at all

**Comment by jacek-marchwicki** [comment]
you but you can look on decoding code in ffmpeg examples
