### ISSUE TITLE
Errors in logcat

### ISSUE THREAD

**Issue by nkhatib** [appunite/AndroidFFmpeg#42]
I am working with eclipse with adt plug-in. I followed your tutorial and I successfully built the ffmpeg library. Then i ran the ffmpegExample and I was able to play an mpeg2 http stream on my samsung galaxy S3. 
The problem: I am trying to play a video with mpeg2 codec from a local server. The protocol is udp (with multicast). This is the URL I used: "udp://@239.100.100.100:1234". Also I tried without the @.
In the logcat i get this error mpeg_decode_postinit() failure.
The player just gives a black screen and doesn't play the video
 how should I fix those errors.
And does ffmpeg supports udp. Please help me with an example.

**Comment by jacek-marchwicki** [comment]
@nkhatib I do not give support about ffmpeg. FFmpeg is separate project that is not modified by this project at all. So if you have some problems with ffmpeg please ask them
