### ISSUE TITLE
make: *** No rule to make target jni/libyuv/source/scale_neon_argb.cc', needed byobj/local/armeabi-v7a/objs/yuv_static/source/scale_neon_argb.o'. Stop.

### ISSUE THREAD

**Issue by nikhilchandran** [appunite/AndroidFFmpeg#44]
Hi Could you please help me to solve this problem.

Thanks

18:17:09 **** Build of configuration Default for project FFmpegLibrary ****
/Users/tiltpvtltd/android-sdks/android-ndk-r8/ndk-build all 
Compile thumb  : ffmpeg-jni <= ffmpeg-jni.c
Compile thumb  : ffmpeg-jni <= player.c
Compile thumb  : ffmpeg-jni <= queue.c
Compile thumb  : ffmpeg-jni <= helpers.c
Compile thumb  : ffmpeg-jni <= jni-protocol.c
Compile thumb  : ffmpeg-jni <= blend.c
Compile++ thumb  : ffmpeg-jni <= convert.cpp
Compile thumb  : ffmpeg-jni <= aes-protocol.c
Compile++ thumb  : yuv_static <= compare.cc
Compile++ thumb  : yuv_static <= compare_common.cc
Compile++ thumb  : yuv_static <= compare_posix.cc
Compile++ thumb  : yuv_static <= convert.cc
Compile++ thumb  : yuv_static <= convert_argb.cc
Compile++ thumb  : yuv_static <= convert_from.cc
Compile++ thumb  : yuv_static <= convert_from_argb.cc
Compile++ thumb  : yuv_static <= cpu_id.cc
Compile++ thumb  : yuv_static <= format_conversion.cc
Compile++ thumb  : yuv_static <= planar_functions.cc
Compile++ thumb  : yuv_static <= rotate.cc
Compile++ thumb  : yuv_static <= rotate_argb.cc
Compile++ thumb  : yuv_static <= row_any.cc
Compile++ thumb  : yuv_static <= row_common.cc
Compile++ thumb  : yuv_static <= row_mips.cc
Compile++ thumb  : yuv_static <= row_posix.cc
Compile++ thumb  : yuv_static <= scale.cc
Compile++ thumb  : yuv_static <= scale_argb.cc
Compile++ thumb  : yuv_static <= scale_mips.cc
Compile++ thumb  : yuv_static <= video_common.cc
Prebuilt       : libgnustl_static.a <= <NDK>/sources/cxx-stl/gnu-libstdc++/libs/armeabi/
StaticLibrary  : libyuv_static.a
Compile arm    : tropicssl <= aes.c
Compile arm    : tropicssl <= arc4.c
Compile arm    : tropicssl <= base64.c
Compile arm    : tropicssl <= bignum.c
Compile arm    : tropicssl <= certs.c
Compile arm    : tropicssl <= debug.c
Compile arm    : tropicssl <= des.c
Compile arm    : tropicssl <= dhm.c
Compile arm    : tropicssl <= havege.c
Compile arm    : tropicssl <= md2.c
Compile arm    : tropicssl <= md4.c
Compile arm    : tropicssl <= md5.c
Compile arm    : tropicssl <= net.c
jni/tropicssl/library/net.c:85:1: warning: "HTONS" redefined
In file included from /Users/tiltpvtltd/android-sdks/android-ndk-r8/platforms/android-14/arch-arm/usr/include/endian.h:31,
                 from /Users/tiltpvtltd/android-sdks/android-ndk-r8/platforms/android-14/arch-arm/usr/include/netinet/in.h:31,
                 from jni/tropicssl/library/net.c:63:
/Users/tiltpvtltd/android-sdks/android-ndk-r8/platforms/android-14/arch-arm/usr/include/sys/endian.h:261:1: warning: this is the location of the previous definition
Compile arm    : tropicssl <= padlock.c
Compile arm    : tropicssl <= rsa.c
Compile arm    : tropicssl <= sha1.c
Compile arm    : tropicssl <= sha2.c
Compile arm    : tropicssl <= sha4.c
Compile arm    : tropicssl <= ssl_cli.c
Compile arm    : tropicssl <= ssl_srv.c
Compile arm    : tropicssl <= ssl_tls.c
Compile arm    : tropicssl <= timing.c
Compile arm    : tropicssl <= x509parse.c
Compile arm    : tropicssl <= xtea.c
Compile arm    : tropicssl <= camellia.c
StaticLibrary  : libtropicssl.a
SharedLibrary  : libffmpeg-jni.so
Install        : libffmpeg-jni.so => libs/armeabi/libffmpeg-jni.so
Prebuilt       : libffmpeg.so <= jni/ffmpeg-build/armeabi/
Install        : libffmpeg.so => libs/armeabi/libffmpeg.so
Compile thumb  : nativetester-jni <= nativetester-jni.c
Compile thumb  : nativetester-jni <= nativetester.c
Compile thumb  : cpufeatures <= cpu-features.c
StaticLibrary  : libcpufeatures.a
SharedLibrary  : libnativetester-jni.so
Install        : libnativetester-jni.so => libs/armeabi/libnativetester-jni.so
Compile thumb  : ffmpeg-jni <= ffmpeg-jni.c
Compile thumb  : ffmpeg-jni <= player.c
Compile thumb  : ffmpeg-jni <= queue.c
Compile thumb  : ffmpeg-jni <= helpers.c
Compile thumb  : ffmpeg-jni <= jni-protocol.c
Compile thumb  : ffmpeg-jni <= blend.c
Compile++ thumb  : ffmpeg-jni <= convert.cpp
Compile thumb  : ffmpeg-jni <= aes-protocol.c
Compile++ thumb  : yuv_static <= compare.cc
Compile++ thumb  : yuv_static <= compare_common.cc
Compile++ thumb  : yuv_static <= compare_posix.cc
Compile++ thumb  : yuv_static <= convert.cc
Compile++ thumb  : yuv_static <= convert_argb.cc
Compile++ thumb  : yuv_static <= convert_from.cc
Compile++ thumb  : yuv_static <= convert_from_argb.cc
Compile++ thumb  : yuv_static <= cpu_id.cc
Compile++ thumb  : yuv_static <= format_conversion.cc
Compile++ thumb  : yuv_static <= planar_functions.cc
Compile++ thumb  : yuv_static <= rotate.cc
Compile++ thumb  : yuv_static <= rotate_argb.cc
Compile++ thumb  : yuv_static <= row_any.cc
Compile++ thumb  : yuv_static <= row_common.cc
Compile++ thumb  : yuv_static <= row_mips.cc
Compile++ thumb  : yuv_static <= row_posix.cc
Compile++ thumb  : yuv_static <= scale.cc
Compile++ thumb  : yuv_static <= scale_argb.cc
Compile++ thumb  : yuv_static <= scale_mips.cc
Compile++ thumb  : yuv_static <= video_common.cc
Compile++ thumb  : yuv_static <= compare_neon.cc
Compile++ thumb  : yuv_static <= rotate_neon.cc
Compile++ thumb  : yuv_static <= row_neon.cc
Compile++ thumb  : yuv_static <= scale_neon.cc
make: *** No rule to make target `jni/libyuv/source/scale_neon_argb.cc', needed by `obj/local/armeabi-v7a/objs/yuv_static/source/scale_neon_argb.o'.  Stop.

**Comment by jacek-marchwicki** [comment]
This should be fixed in current version
