### ISSUE TITLE
Cannot build shared libraries

### ISSUE THREAD

**Issue by vijayhubino** [appunite/AndroidFFmpeg#47]
I have followed the steps given to build FFmpegLibrary. But when i run ./build_android.sh, i am getting an exception  as "./configure : No such file or directory" in the below code.

cd vo-amrwbenc
	./configure \
	    --prefix=$(pwd)/$PREFIX \
	    --host=$ARCH-linux \
	    --disable-dependency-tracking \
	    --disable-shared \
	    --enable-static \
	    --with-pic \
	    $ADDITIONAL_CONFIGURE_FLAG \
	    || exit 1

I have downloaded and added the submodules under jni from the path given in the .gitmodules file. Is there any builded version of FFmpegLibrary available?

**Comment by jacek-marchwicki** [comment]
Not enough informations ...
