### ISSUE TITLE
FFmpeg build error

### ISSUE THREAD

**Issue by vijayhubino** [appunite/AndroidFFmpeg#49]
I followed the steps given at the link https://github.com/appunite/AndroidFFmpeg to build the given example.When i run the build_android.sh i am getting the following exception.
./build_android.sh: line 72: ./configure: No such file or directory

I am spent lot of time in building this example.Any help is appreciated.

**Comment by mtcdn-gmail** [comment]
@vijayhubino : is your issue was resolved "./build_android.sh: line 72: ./configure: No such file or directory"

**Comment by mtcdn-gmail** [comment]
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ accepts -g... yes
checking for /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ option to accept ISO C89... none needed
checking dependency style of /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/... none
checking dependency style of /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/... none
checking for /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ option to accept ISO C99... -std=gnu99
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99... /root/android_ndk/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld
checking if the linker (/root/android_ndk/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm
checking the name lister (/root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to arm-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /root/android_ndk/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld option to reload object files... -r
checking for arm-linux-objdump... no
checking for objdump... objdump
configure: WARNING: using cross tools not prefixed with host triplet
checking how to recognize dependent libraries... pass_all
checking for arm-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-linux-ar... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar
checking for archiver @FILE support... @
checking for arm-linux-strip... (cached) /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
checking for arm-linux-ranlib... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib
checking command to parse /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm output from /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 object... ok
checking for sysroot... no
checking for arm-linux-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 static flag -static works... no
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 supports -c -o file.o... yes
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 linker (/root/android_ndk/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vo-amrwbenc.pc
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
test -z "libvo-amrwbenc.la" || rm -f libvo-amrwbenc.la
rm -f "./so_locations"
rm -rf .libs _libs
rm -f *.o
rm -f *.lo
  CC     wrapper.lo
  CC     cmnMemory.lo
  CC     autocorr.lo
  CC     az_isp.lo
  CC     bits.lo
  CC     c2t64fx.lo
  CC     c4t64fx.lo
  CC     convolve.lo
  CC     cor_h_x.lo
  CC     decim54.lo
  CC     deemph.lo
  CC     dtx.lo
  CC     g_pitch.lo
  CC     gpclip.lo
  CC     homing.lo
  CC     hp400.lo
  CC     hp6k.lo
  CC     hp50.lo
  CC     hp_wsp.lo
  CC     int_lpc.lo
  CC     isp_az.lo
  CC     isp_isf.lo
  CC     lag_wind.lo
  CC     levinson.lo
  CC     log2.lo
  CC     lp_dec2.lo
  CC     math_op.lo
  CC     mem_align.lo
  CC     oper_32b.lo
  CC     p_med_ol.lo
  CC     pit_shrp.lo
  CC     pitch_f4.lo
  CC     pred_lt4.lo
  CC     preemph.lo
  CC     q_gain2.lo
  CC     q_pulse.lo
  CC     qisf_ns.lo
  CC     qpisf_2s.lo
  CC     random.lo
  CC     residu.lo
  CC     scale.lo
  CC     stream.lo
  CC     syn_filt.lo
  CC     updt_tar.lo
  CC     util.lo
  CC     voAMRWBEnc.lo
  CC     voicefac.lo
  CC     wb_vad.lo
  CC     weight_a.lo
  CCLD   libvo-amrwbenc.la
make[1]: Entering directory `/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc'
test -z "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib" || /bin/mkdir -p "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib"
test -z "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/include/vo-amrwbenc" || /bin/mkdir -p "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/include/vo-amrwbenc"
test -z "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib/pkgconfig" || /bin/mkdir -p "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib/pkgconfig"
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libvo-amrwbenc.la '/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib'
 /usr/bin/install -c -m 644 enc_if.h '/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/include/vo-amrwbenc'
 /usr/bin/install -c -m 644 vo-amrwbenc.pc '/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib/pkgconfig'
libtool: install: /usr/bin/install -c .libs/libvo-amrwbenc.lai /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib/libvo-amrwbenc.la
libtool: install: /usr/bin/install -c .libs/libvo-amrwbenc.a /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib/libvo-amrwbenc.a
libtool: install: chmod 644 /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib/libvo-amrwbenc.a
libtool: install: /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib/libvo-amrwbenc.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/hadoop/bin:/usr/lib/pig/pig-0.7.0/bin:/adt-bundle-linux/sdk/platform-tools:/root/adt-bundle-linux/sdk/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/hadoop/bin:/usr/lib/pig/pig-0.7.0/bin:/root/root/android_ndk/android-ndk-r10c:/root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/:/sbin" ldconfig -n /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
test -z "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/bin" || /bin/mkdir -p "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc/../ffmpeg-build/armeabi/bin"
make[1]: Leaving directory `/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc'
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-strip... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-unknown-linux-gnu
checking for style of include used by make... GNU
checking for arm-linux-gcc... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ accepts -g... yes
checking for /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ option to accept ISO C89... none needed
checking dependency style of /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/... none
checking dependency style of /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/... none
checking for /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ option to accept ISO C99... -std=gnu99
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99... /root/android_ndk/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld
checking if the linker (/root/android_ndk/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm
checking the name lister (/root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to arm-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /root/android_ndk/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld option to reload object files... -r
checking for arm-linux-objdump... no
checking for objdump... objdump
configure: WARNING: using cross tools not prefixed with host triplet
checking how to recognize dependent libraries... pass_all
checking for arm-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-linux-ar... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar
checking for archiver @FILE support... @
checking for arm-linux-strip... (cached) /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
checking for arm-linux-ranlib... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib
checking command to parse /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm output from /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 object... ok
checking for sysroot... no
checking for arm-linux-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 static flag -static works... no
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 supports -c -o file.o... yes
checking if /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/root/android_ndk/android-ndk-r10c//platforms/android-5/arch-arm/ -std=gnu99 linker (/root/android_ndk/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vo-aacenc.pc
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
test -z "libvo-aacenc.la" || rm -f libvo-aacenc.la
rm -f "./so_locations"
rm -rf .libs _libs
rm -f *.o
rm -f *.lo
  CC     cmnMemory.lo
  CC     basicop2.lo
  CC     oper_32b.lo
  CC     aac_rom.lo
  CC     aacenc.lo
  CC     aacenc_core.lo
  CC     adj_thr.lo
  CC     band_nrg.lo
  CC     bit_cnt.lo
  CC     bitbuffer.lo
  CC     bitenc.lo
  CC     block_switch.lo
  CC     channel_map.lo
  CC     dyn_bits.lo
  CC     grp_data.lo
  CC     interface.lo
  CC     line_pe.lo
  CC     memalign.lo
  CC     ms_stereo.lo
  CC     pre_echo_control.lo
  CC     psy_configuration.lo
  CC     psy_main.lo
  CC     qc_main.lo
  CC     quantize.lo
  CC     sf_estim.lo
  CC     spreading.lo
  CC     stat_bits.lo
  CC     tns.lo
  CC     transform.lo
  CCLD   libvo-aacenc.la
make[1]: Entering directory `/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc'
test -z "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib" || /bin/mkdir -p "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib"
test -z "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/include/vo-aacenc" || /bin/mkdir -p "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/include/vo-aacenc"
test -z "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib/pkgconfig" || /bin/mkdir -p "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib/pkgconfig"
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libvo-aacenc.la '/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib'
 /usr/bin/install -c -m 644 vo-aacenc.pc '/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib/pkgconfig'
 /usr/bin/install -c -m 644 ./common/include/cmnMemory.h ./common/include/voAAC.h ./common/include/voAMRWB.h ./common/include/voAudio.h ./common/include/voIndex.h ./common/include/voMem.h ./common/include/voType.h '/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/include/vo-aacenc'
libtool: install: /usr/bin/install -c .libs/libvo-aacenc.lai /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib/libvo-aacenc.la
libtool: install: /usr/bin/install -c .libs/libvo-aacenc.a /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib/libvo-aacenc.a
libtool: install: chmod 644 /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib/libvo-aacenc.a
libtool: install: /root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib/libvo-aacenc.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/hadoop/bin:/usr/lib/pig/pig-0.7.0/bin:/adt-bundle-linux/sdk/platform-tools:/root/adt-bundle-linux/sdk/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/hadoop/bin:/usr/lib/pig/pig-0.7.0/bin:/root/root/android_ndk/android-ndk-r10c:/root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/:/root/android_ndk/android-ndk-r10c//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/:/sbin" ldconfig -n /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
test -z "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/bin" || /bin/mkdir -p "/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc/../ffmpeg-build/armeabi/bin"
make[1]: Leaving directory `/root/Downloads/testing/AndroidFFmpeg/FFmpegLibrary/jni/vo-aacenc'
configure: WARNING: unrecognized options: --disable-shared, --enable-static, --with-pic
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../..


I am getting one issue of cross compiler configure
