### ISSUE TITLE
jni_player_seek problem

### ISSUE THREAD

**Issue by soumyarout** [appunite/AndroidFFmpeg#50]
Hi,

First of all thanks for creating this custom library. Its really great and easy to use.

I was working in a simple player  where I need to play small videos whose length is around 5 - 20 secs. Video is playing fine but when I try for seeking in my seekbar by calling seekNative it's not working. Means it is not returning the video frames. I have tried for a long duration video of 15 min. The seek bar works in this case after seeking a video around 30-60 secs forward. Is there any fixed time duration mentioned for video seeking ?

Could you please help me out how can I achieve the video seeking task for small length videos using AndroidFFMPEG library.

**Comment by jacek-marchwicki** [comment]
@soumyarout please ask your company to share your knowledge with us. we gave a lot of our work to opensource world to solve peoples problems. It just rude to ask for help and say that you will return nothing to others.

If you have some help you need to provide video that causing issue.
