### ISSUE TITLE
debugging library

### ISSUE THREAD

**Issue by sarinsukumar** [appunite/AndroidFFmpeg#54]
Hi,
Can you please tell , how to debug the native code in ffmpeg library in using eclipse or command line. I am trying to put a break point in c code and trying to debug the library player.c.
I am able to debug library class files. Can you please tell me how to do this or any information regarding how you did debugging your code while developing.

Thank you very much for making such a useful library and sharing it.

Best regards
Sarin sukumar A

**Comment by jacek-marchwicki** [comment]
Currently I'm only using log's for debugging.

look on those varaibles:
```c
#define FFMPEG_LOG_LEVEL AV_LOG_WARNING
#define LOG_LEVEL 2
```
