### ISSUE TITLE
can you please comment on following warning ?

### ISSUE THREAD

**Issue by sarinsukumar** [appunite/AndroidFFmpeg#56]
[2013-09-13 07:29:26 - FFmpegLibrary] Could not find FFmpegLibrary.apk!

I am getting this while running the code. is this a problem ? or can i ignore it ?

**Comment by jacek-marchwicki** [comment]
I do not know here this issue happen? 
What did you do that this warning happen?
You can try use new library - now we use gradle to compile everything,
