### ISSUE TITLE
cygwin_nt-6.1-wow64-x86/bin/arm-linux-androideabi-gcc no such a file or directory

### ISSUE THREAD

**Issue by DariusArya** [appunite/AndroidFFmpeg#66]
trying to install ffmpeg on Cygwin on Windows 7, 64bit. 
in /android-ndk-r9c-windows-x86_64/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/  
  I have windows-x86_64 directory in which the compiler does exist. 
 but for some reason that I don't understand, the configure looks for cygwin_nt-6.1-wow64-x86/ which doesn't exist. 
Does any body know how can I overcome this problem? either get the folder, or make it so that it looks for right directory?

**Comment by jacek-marchwicki** [comment]
There is a waste of time trying to compile ffmpeg on windows, so please use linux or mac
