### ISSUE TITLE
Codecs for bik, smk, mov, qt, riff, ts video formats.

### ISSUE THREAD

**Issue by drakariis** [appunite/AndroidFFmpeg#68]
Hi all! I need to play bik, smk, mov, qt, riff, ts video formats. What type of encoders, decoders, muxers, demuxers i need to add into build_android.sh script to be able to play them. I executed commands --list-encoders, --list-decoders, but there is a very big list of them, what of them i need to add?

**Comment by jacek-marchwicki** [comment]
Please ask ffmpeg guys
