### ISSUE TITLE
How can I decrease apk size of FFmpegPlayer

### ISSUE THREAD

**Issue by drakariis** [appunite/AndroidFFmpeg#69]
Hi! Is there any way to change the apk size of this player. Now It is 26 Mb. May be delete some libs?

**Comment by jacek-marchwicki** [comment]
Now we use gradle so you can easly use ABIs Splits "http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits" and upload multiple apk's to playstore so user will only have libs in architecture for theirs phones.
You can also remove some codecs from ffmpeg build.
