### ISSUE TITLE
LOCAL_SRC_FILES points to a missing file

### ISSUE THREAD

**Issue by Darasaini** [appunite/AndroidFFmpeg#7]
/FFmpegLibrary$ /home/appaspect/android-ndk-r8b/ndk-build
Android NDK: ERROR:jni/yuv2rgb/Android.mk:ffmpeg-prebuilt: LOCAL_SRC_FILES points to a missing file  
Android NDK: Check that jni/yuv2rgb/ffmpeg-build/armeabi/libffmpeg.so exists  or that its path is correct  
android-ndk-r8b/build/core/prebuilt-library.mk:43: **\* Android NDK: Aborting    .  Stop.

**Comment by mtcdn-gmail** [comment]
I am using ubuntu 12.04 and i done all generated all the libs from readme file and finally when i run ./build_android.sh file i get following error:
./build_android.sh: line 72: ./configure: No such file or directory

Can you please tell how i can overcome this problem

**Comment by jacek-marchwicki** [comment]
git probably didn't checked out submodules

https://github.com/appunite/AndroidFFmpeg/blob/master/FFmpegLibrary/jni/build_android.sh#L70
look, script try to get "vo-amrwbenc" directory, than try to run configure script - looks like it does not exists.
