### ISSUE TITLE
Fixes for building on OSX

### ISSUE THREAD

**Issue by fscz** [appunite/AndroidFFmpeg#70]
1 
in 'vo-aacenc' autoreconf failes
fix:
- add AUTOMAKE_OPTIONS = subdir-objects to top of Makefile.am
- autoconf --add-missing
- autoreconf

2
in 'vo-amrwbenc' autoreconf failes
fix:
- add AUTOMAKE_OPTIONS = subdir-objects to top of Makefile.am
- autoconf --add-missing
- autoreconf

3
'./build_android.sh' complains about the ccompiler not working
fix:
- open build_android.sh, adjust PREBUILT variable (probably something like)
PREBUILT=$NDK/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64

4
(this is probably only relevant if you are using android-ndk-r9+)
'./build_android.sh' complains about unknown linker option 'noexecstack'
fix:
- open build_android.sh, search for '-z, noexecstack' and change to '-z noexeckstack'
- open build_android.sh, search for '--warn-once' and remove it

**Comment by jacek-marchwicki** [comment]
I use mac and now ffmpeg builds without problems so I will close this issue
