### ISSUE TITLE
Android NDK r10 support

### ISSUE THREAD

**Issue by KhArtNJava** [appunite/AndroidFFmpeg#76]
Hi.
Did you plan to add supportof the NDK r10 with arm-linux-androideabi-4.8 toolchain?
With  NDK r10 with arm-linux-androideabi-4.8 toolchain I can't compile project:

CC      libavcodec/dcadec.o
CC      libavcodec/dcadsp.o
CC      libavcodec/dcaenc.o
CC      libavcodec/dct.o
libavcodec/dcaenc.c: In function 'encode_init':
libavcodec/dcaenc.c:228:36: warning: iteration 256u invokes undefined behavior [-Waggressive-loop-optimizations]
         lfe_fir_64i[i] = lfe_fir_64[i] * (1 << 25); //float -> int32_t
                                    ^
libavcodec/dcaenc.c:227:5: note: containing loop
     for (i = 0; i < 512; i++)
     ^
In file included from libavcodec/dcadec.c:49:0:
libavcodec/dcadec.c: In function 'dca_xbr_parse_frame':
libavcodec/arm/dca.h:36:5: error: can't find a register in class 'CORE_REGS' while reloading 'asm'
     __asm__ ("smmul   %8,  %14, %18           \n"
     ^
libavcodec/arm/dca.h:36:5: error: 'asm' operand has impossible constraints
libavcodec/dcadec.c:1884: confused by earlier errors, bailing out
make: *** [libavcodec/dcadec.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by jacek-marchwicki** [comment]
Currently no plans, please use 8e
