### ISSUE TITLE
when I run ./build_android.sh, how can i resove it thanks

### ISSUE THREAD

**Issue by panbin** [appunite/AndroidFFmpeg#77]
configure: error: in `/root/AndroidFFmpeg/FFmpegLibrary/jni/vo-amrwbenc':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by jacek-marchwicki** [comment]
you need to look on FFmpegLibrary/jni/vo-amrwbenc/config.log to see what happen.. 
Look in this file neer "compiler cannot create executables" message.
