### ISSUE TITLE
freetype directory not found

### ISSUE THREAD

**Issue by siddhpuraamitr** [appunite/AndroidFFmpeg#85]
I have try to execute following command

setup freetype environemtn

cd freetype

but freetype is not found

after that I have execute

 cd freetype2/

and then

amit@amit-System-Product-Name:~/AndroidFFmpeg/FFmpegLibrary/jni/freetype2$ ./autogen.sh

but below error is coming out

./autogen.sh: 1: ./autogen.sh: aclocal: not found
./autogen.sh: 55: test: -lt: argument expected
./autogen.sh: 59: test: -gt: argument expected
./autogen.sh: 67: test: -lt: argument expected
./autogen.sh: 71: test: -gt: argument expected
./autogen.sh: 1: ./autogen.sh: libtoolize: not found
./autogen.sh: 55: test: -lt: argument expected
./autogen.sh: 59: test: -gt: argument expected
./autogen.sh: 67: test: -lt: argument expected
./autogen.sh: 71: test: -gt: argument expected
./autogen.sh: 1: ./autogen.sh: autoconf: not found
./autogen.sh: 55: test: -lt: argument expected
./autogen.sh: 59: test: -gt: argument expected
./autogen.sh: 67: test: -lt: argument expected
./autogen.sh: 71: test: -gt: argument expected
generating `configure.ac'
running `aclocal -I . --force'
./autogen.sh: 1: eval: aclocal: not found
error while running `aclocal -I . --force'

**Comment by julianonunes** [comment]
Got the same problem here

**Comment by kwojtaszek** [comment]
you need to install autoconf and libtool using brew: http://brew.sh
