### ISSUE TITLE
Cloud not git push Github and git push gitbook  

### ISSUE THREAD

**Issue by cici1989** [appunite/AndroidFFmpeg#87]
abcdedeMacBook-Pro:my-new chenfeichi$ git push 
ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jacek-marchwicki** [comment]
"Could not resolve hostname github.com" this is quite meaningful, do you have a network access?
