### ISSUE TITLE
m3u8 can't play any

### ISSUE THREAD

**Issue by kulik** [appunite/AndroidFFmpeg#97]
i am tryed to play each movie from example. it's tell me can't load stream. then i am put my url
http://hlithls-i.akamaihd.net/hls/live/207407/Training1/index.m3u8 it is has encoded with next codec http://screencloud.net/v/hoZu. and i have next logs  http://pastebin.com/TJxNjVFZ   Look like video has loaded, but i see just black screen.

**Comment by kulik** [comment]
i used default configuration.

**Comment by manzhda** [comment]
Hi. I ran into the same issue with m3u8.

**Comment by jacek-marchwicki** [comment]
I think this video can be played but it have quite high resolution 1080p so without hardware decoding decoding will be impossible

**Comment by Zo2m4bie** [comment]
I tried different streams and no one worked. When I tried I alwayes received 
 E/ffmpeg﹕ Estimating duration from bitrate, this may be inaccurate

On some stream I received 
 E/ffmpeg﹕ Estimating duration from bitrate, this may be inaccurate
 E/ffmpeg﹕ No accelerated colorspace conversion found from yuv420p to rgba.

One of the streams: http://fast-fortress-4864.herokuapp.com/str108.setplex.net/fastv_2psh/PinkFamilyglobal_rly_greece_103/mojtube.m3u8

**Comment by Zo2m4bie** [comment]
Also I tried to open sample, but http://devimages.apple.com.edgekey.net/resources/http-streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8 and https://devimages.apple.com.edgekey.net/resources/http-streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8 didn't work. I received Could not  open stream dialog and in log I had 

 E/player.c﹕ player_set_data_source Could not open video file: https://devimages.apple.com.edgekey.net/resources/http-streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8 (-1330794744: Protocol not found)

**Comment by jacek-marchwicki** [comment]
@Zo2m4bie booth files doesn't exists

**Comment by bsysop** [comment]
At this moment just MP4 files can play for me, if Live M3u8 this don't play!.

Any ideia why?
